config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'users/about', to: 'pages#about'
  get 'users/staff', to: 'pages#staff'
  get 'users/tracker', to: 'pages#tracker'
  get 'users/index', to: 'pages#index'
  get 'users/pokequiz', to: 'pages#pokequiz'

  root 'home#index'
  get 'home/index'
  get '/about', to: 'pages#about'
  get '/staff', to: 'pages#staff'
  get '/tracker', to: 'pages#tracker'
  get '/index', to: 'pages#index'
  get '/pokequiz', to: 'pages#pokequiz'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Article.all
    # Your controller logic here, if any
  end

  def about
  end

  def staff
  end

  def tracker
  end

  def pokequiz
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :avatar)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def create
    super do |resource|
      redirect_to root_path # Redirect to the root path after sign-in
      return
    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <script src="https://kit.fontawesome.com/fe39825268.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>The Golden Times</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "styles", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "pokemon", "script", "quiz", "nextpage" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render partial: 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
 <div class="container">
   <div class="content  px-3 py-3">
      <h2  class="mt-5 mb-5">About us</h2>
      <p>Welcome to the Golden Times, the Pokémon News Agency from Goldenrod City and your premier source for all things Pokémon-related! Established as an extension of the renowned Pokémon Radio network headquartered in Goldenrod City, our agency has been dedicated to delivering timely and accurate news coverage from across the Pokémon world.
        Our journey began with a simple mission: to provide trainers, enthusiasts, and fans with the latest updates, stories, and developments from the vast and diverse Pokémon universe.<br><br> From exciting tournament results to groundbreaking research discoveries, we strive to bring you the most comprehensive coverage possible, ensuring that you stay informed and engaged with the ever-evolving world of Pokémon.
        As an affiliate of Pokémon Radio, our agency benefits from the extensive resources and expertise of our parent company. With access to a network of correspondents, reporters, and analysts stationed in key locations throughout the Pokémon world, we are able to deliver breaking news and exclusive insights in real-time, keeping you ahead of the curve and immersed in the pulse of the Pokémon community.
        But our commitment to excellence doesn't stop there. At the Pokémon News Agency, we pride ourselves on upholding the highest standards of journalistic integrity and professionalism.<br><br> Every story we cover undergoes rigorous fact-checking and verification to ensure accuracy and reliability, so you can trust that the information you receive from us is always credible and trustworthy.
        In addition to our news coverage, we also offer a variety of engaging features, including interviews with top trainers, in-depth analyses of Pokémon battles and strategies. Whether you're a seasoned veteran or a newcomer to the world of Pokémon, there's something for everyone here at the Pokémon News Agency.
        <br><br>If you enjoy our site and the daily news articles, please consider donating. Every little bit helps!
      </p>
      <a href="https://www.paypal.com/donate/?hosted_button_id=QCWFD79VTG9SY" target="_blank"><button class="donate-button">Donate</button></a>
   </div>

</div>

app/views/pages/pokequiz.html.erb
<div class="container">
      <div class="content2">
      <h2 class="mt-5 mb-5">PokéQuiz</h2>
      <p>Answer questions correctly in every town to proceed to the next one. All questions are about FireRed and LeafGreen, unless defined otherwise. Read the questions carefully, if you make a mistake, you have to start over!<b><br><br>IF</b> you manage to beat the quiz, you will receive a printable certificate with a randomly chosen Pokemon, some more rare than others. There are close to 136.000 unique certificates!
     Some useful websites that you can use to aid you in this quiz: <br>(will open in a new window)</p>
      <a href="https://bulbapedia.bulbagarden.net/" target="_blank" class="gradient-link">Bulbapedia</a>
      <a href="https://www.serebii.net/pokemon/" target="_blank" class="gradient-link">Serebii</a>
      <a href="https://strategywiki.org/wiki/Pok%C3%A9mon_FireRed_and_LeafGreen" target="_blank" class="gradient-link">Strategy Wiki</a><br>

      <div class="congrats" style="display: none;"><p>Congratulations on finishing the quiz!<br>You can click on the certificate to print it</p></div>
      <label for="username" id="userLabel">Hello Trainer! What's your first name?</label>
      <input type="text" id="usernameInput" maxlength="20">
        <button onclick="submitName()" id="userButton">Start Quiz!</button>


      <div class="wrapper" style="display: none;">
         <div class="left-column">
            <div class="left-square square14"></div>
            <div class="left-square square13"></div>
            <div class="left-square square12"></div>
            <div class="left-square square11"></div>
            <div class="left-square square10"></div>
            <div class="left-square square9"></div>
            <div class="left-square square8"></div>
            <div class="left-square square7"></div>
            <div class="left-square square6"></div>
            <div class="left-square square5"></div>
            <div class="left-square square4"></div>
            <div class="left-square square3"></div>
            <div class="left-square square2"></div>
            <div class="left-square square1">Pallet Town 🔒</div>
         </div>
         <div class="quiz-container">
            <button id="next-btn" style="display: none;">Next</button>
              <!-- Added Next Level button -->
             <div id="result" style="display: none;"></div>
             <button id="next-level-btn" style="display: none;">Next Level</button>
             <button id="restart-btn" style="display: none;">Restart</button>
             <button id="deactivate-btn" style="display: none;">Deactivate 2 Options</button>
             <button id="proceedToEliteButton" class="proceed-button"  style="display: none;">Proceed to Elite 4</button>
             <div id="question-container"></div>
               <h2 id="question"></h2>
               <div id="options"></div>
           </div>
         <div class="right-column">
            <div class="right-square square28"></div>
            <div class="right-square square27"></div>
            <div class="right-square square26"></div>
            <div class="right-square square25"></div>
            <div class="right-square square24"></div>
            <div class="right-square square23"></div>
            <div class="right-square square22"></div>
            <div class="right-square square21"></div>
            <div class="right-square square20"></div>
            <div class="right-square square19"></div>
            <div class="right-square square18"></div>
            <div class="right-square square17"></div>
            <div class="right-square square16"></div>
            <div class="right-square square15"></div>
         </div>

       </div>
       <div class="bottom" style="display: none;">
            <div class="elite-member"></div>
            <div class="elite-member"></div>
            <div class="elite-member"></div>
            <div class="elite-member"></div>
       </div>
    </div>
   </div>
</div>

app/views/pages/staff.html.erb
<div class="container">
      <div class="content">
    <h2 class="mt-5 mb-5">Our staff</h2>
    <h3 class="mb-4">Each member of the Golden Times News Station brings their unique skills, experiences, and love for<br> Pokémon to deliver top-quality news coverage to the viewers.<br><br>In case you have any questions or feedback, please contact us at <a href="mailto:news@thegoldentimes.ch">news@thegoldentimes.ch</a></h3>

      <div class="staff-member">
        <div class="staff-details">
          <div class="staff-info">
            <%= image_tag "staff/kevinsoriano.png", class: "staff-image" %>
            <p class="staff-name">Kevin Stal</p>
            <p class="staff-role">Chief Editor</p>
            <p class="staff-hometown">Hometown: Azalea Town</p>
            <p class="staff-favorite">Favorite Pokemon: Aerodactyl</p>
            <br>
          </div>
       <div class="staff-description">
          <p>Kevin, a seasoned journalist, meticulously sifts through piles of articles, ensuring each word resonates with precision. His discerning eye catches even the subtlest of errors, earning him the respect of his peers.<br><br> With a passion for storytelling, he weaves narratives that captivate readers and shape the editorial direction. Behind the scenes, Kevin's dedication fuels the publication's success, making him an invaluable asset to the team.</p>
        </div>
     </div>
</div>

<div class="staff-member">
  <div class="staff-details">


    <div class="staff-info">
       <%= image_tag "staff/stone.png", class: "staff-image" %>
     <p class="staff-name">Maya Stone</p>
      <p class="staff-role">Lead Reporter</p>
      <p class="staff-hometown">Hometown: Lilycove City</p>
      <p class="staff-favorite">Favorite Pokemon: Gardevoir</p>
      <br>

    </div>
<div class="staff-description">
      <p>Maya's typewriter clicks with the rhythm of breaking news as she dashes from one scoop to the next. Her relentless pursuit of truth drives her to uncover stories that shine a light on society's complexities. With a keen eye for detail and a knack for storytelling, Maya crafts articles that resonate with readers and provoke thought.<br><br> As the lead reporter, she embodies journalistic integrity and fearlessly challenges the status quo, earning admiration from both colleagues and readers alike.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">
    <div class="staff-info">
      <%= image_tag "staff/frost.png", class: "staff-image" %>
      <p class="staff-name">Xander Frost</p>
      <p class="staff-role">Senior Correspondent</p>
      <p class="staff-hometown">Hometown: Snowpoint City</p>
      <p class="staff-favorite">Favorite Pokemon: Abomasnow</p>
      <br>

    </div>
    <div class="staff-description">
       <p>Xander's pen glides effortlessly across the page, translating the pulse of the city into compelling narratives. As a seasoned correspondent, he navigates the intricate web of politics and intrigue with finesse, uncovering stories that spark conversation.<br><br> With a penchant for investigative journalism, Xander fearlessly pursues the truth, exposing corruption and championing transparency. His unwavering dedication to his craft and commitment to journalistic integrity make him a trusted voice in the media landscape.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">

    <div class="staff-info">
      <%= image_tag "staff/brooks.png", class: "staff-image" %>
       <p class="staff-name">Avery Brooks</p>
      <p class="staff-role">Investigative Journalist</p>
      <p class="staff-hometown">Hometown: Goldenrod City</p>
      <p class="staff-favorite">Favorite Pokemon: Houndoom</p>

         </div>
 <div class="staff-description">
       <p>Avery's investigative prowess pierces through layers of deception, uncovering truths hidden in the shadows. Armed with a relentless curiosity and a keen intellect, he delves deep into the heart of stories, exposing corruption and holding the powerful accountable.<br><br> His tenacity in pursuit of justice earns him both admiration and respect among his peers. With every exposé, Avery reaffirms his commitment to uncovering the truth and giving voice to the voiceless.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">
    <div class="staff-info">
      <%= image_tag "staff/reporter2.png", class: "staff-image" %>
      <p class="staff-name">Fiona Ocean</p>
      <p class="staff-role">Field Reporter</p>
      <p class="staff-hometown">Hometown: Mossdeep City</p>
      <p class="staff-favorite">Favorite Pokemon: Milotic</p>

        </div>
    <div class="staff-description">
       <p>Fiona's camera lens captures the raw emotion of the human experience, transforming ordinary moments into compelling stories. With a passion for storytelling and an eye for detail, she ventures into the heart of communities, shedding light on untold narratives. <br><br>Whether she's documenting local heroes or covering breaking news, Fiona's empathy and dedication shine through in every frame. Her ability to connect with people on a personal level makes her a beloved figure in the communities she serves.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">

    <div class="staff-info">
      <%= image_tag "staff/camera.png", class: "staff-image" %>
     <p class="staff-name">Caleb Everest</p>
      <p class="staff-role">Cameraman</p>
      <p class="staff-hometown">Hometown: Ever Grande City</p>
      <p class="staff-favorite">Favorite Pokemon: Flygon</p>
      <br>
    </div>
   <div class="staff-description">
       <p>Caleb's steady hand and keen eye for composition bring stories to life through the lens of his camera. From bustling city streets to remote landscapes, he captures the essence of every scene with precision and artistry. Behind the camera, Caleb's quiet demeanor belies his passion for visual storytelling, as he tirelessly strives to capture the perfect shot.<br><br> His technical expertise and creative vision make him an indispensable member of the team, elevating every story he touches.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">
    <div class="staff-info">
      <%= image_tag "staff/swift.png", class: "staff-image" %>
      <p class="staff-name">Nora Swift</p>
      <p class="staff-role">Interviewer</p>
      <p class="staff-hometown">Ecruteak City</p>
      <p class="staff-favorite">Favorite Pokemon: Lickitung</p>
      <br>
    </div>
    <div class="staff-description">
       <p>Nora's warm smile and genuine curiosity put her interview subjects at ease, allowing them to open up and share their stories with honesty and vulnerability. With a knack for asking the right questions, she uncovers the heart of every narrative, giving voice to the voiceless and amplifying diverse perspectives.<br><br> As an interviewer, Nora's empathy and intuition guide her interactions, fostering meaningful connections and fostering understanding. Her dedication to telling stories with integrity and compassion makes her a trusted voice in journalism.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">

    <div class="staff-info">
      <%= image_tag "staff/news2.png", class: "staff-image" %>
      <p class="staff-name">Isaac Reed</p>
      <p class="staff-role">News Anchor</p>
      <p class="staff-hometown">Hometown: Castelia City</p>
      <p class="staff-favorite">Favorite Pokemon: Serperior</p>

    </div>
<div class="staff-description">
     <p>Isaac's commanding presence and smooth delivery make him a trusted source of information for viewers across the region. As the news anchor, he navigates the fast-paced world of broadcast journalism with grace and professionalism, delivering breaking news with clarity and authority. Behind the desk, Isaac's journalistic integrity and dedication to accuracy shine through in every broadcast, earning him the respect and admiration of his audience.<br><br> With his finger on the pulse of current events, Isaac keeps viewers informed and engaged, guiding them through the day's top stories with confidence.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">
    <div class="staff-info">
      <%= image_tag "staff/weather.png", class: "staff-image" %>
      <p class="staff-name">Luna Skylark</p>
      <p class="staff-role">Weather Reporter</p>
      <p class="staff-hometown">Hometown: Fortree City</p>
      <p class="staff-favorite">Favorite Pokemon: Altaria</p>
    </div>
    <div class="staff-description">
       <p>Luna's infectious enthusiasm and meteorological expertise make her a ray of sunshine on even the cloudiest of days. As the weather reporter, she brings the forecast to life with her bubbly personality and captivating on-air presence. With a keen eye for atmospheric patterns and a passion for science, Luna delivers accurate and engaging weather updates that keep viewers informed and entertained.<br><br> It doesn't matter if she's tracking storms or forecasting sunshine, Luna's warmth and professionalism make her a beloved fixture in the newsroom.</p>
    </div>
  </div>
</div>

<div class="staff-member">
  <div class="staff-details">

    <div class="staff-info">
      <%= image_tag "staff/dexter.png", class: "staff-image" %>
      <p class="staff-name">Dexter Blaze</p>
      <p class="staff-role">Editor</p>
      <p class="staff-hometown">Hometown: Lavaridge Town</p>
      <p class="staff-favorite">Favorite Pokemon: Groudon</p>
    </div>
<div class="staff-description">
      <p>Dexter's discerning eye and meticulous attention to detail ensure that every article that crosses his desk meets the highest standards of quality. As the editor, he shapes the publication's editorial direction with precision, guiding the team to produce content that informs, engages, and inspires readers. With a keen understanding of storytelling techniques and journalistic ethics, Dexter transforms raw material into polished narratives that captivate audiences. <br><br>Behind the scenes, his leadership and expertise drive the newsroom forward, fostering a culture of excellence and collaboration among his colleagues.</p>
    </div>
  </div>
</div>
<button class="donate-button">Donate</button>
</div>
</div>

</div>

app/views/pages/tracker.html.erb
      <div class="container">
        <div class="content3">
        <h2 class="mt-5 mb-5">Pokémon Tracker</h2>
        <p>The Pokémon Tracker for speedrunners is a user-friendly web page designed to assist players in tracking their progress in capturing Pokemon during speedruns. It features a grid layout displaying all Pokemon sprites, allowing players to easily visualize their collection. This intuitive design streamlines the tracking process, enabling speedrunners to efficiently manage their progress and optimize their gameplay strategies.</p>
        <h2 class="mt-3">INSTRUCTIONS:</h2>
         <br>
        <p><b>Step 1:</b> Click the Pokémon you want to track</p>
        <br>
        <p><b>Step 2:</b> Left click to remove a Pokémon from the box</p>
        <br>
        <p><b>Step 3:</b> Right click once to mark a Pokémon as planned</p>
        <br>
        <p><b>Step 4:</b> Right click twice to mark a Pokémon as caught</p>
        <br>
        <p><b>Step 5:</b> Right click thrice to unmark a Pokémon</p>
        <br>
         <div id="color-selector">
          <label for="background-color"><b>Step 6</b>: Click to pick a color:</label>
          <input type="color" id="background-color">
        </div>

        <div class="boxtop">
            <div id="counter-container">
                <p><span id="blue-counter"><b>0</b></span> Pokémon planned and
                <span id="pink-counter"><b>0</b></span> Pokémon caught</p>
            </div>
        </div>


        <div class="pokebox"></div>

        <h2>FireRed & LeafGreen</h2>
        <%= render partial: 'shared/pokemon_sprites_normal' %>
        <h2>FireRed & LeafGreen Shiny</h2>
        <%= render partial: 'shared/pokemon_sprites_shiny' %>
        <h2>Gold & Silver</h2>
        <%= render partial: 'shared/pokemon_sprites_normal2' %>
        <h2>Gold & Silver - Shiny</h2>
        <%= render partial: 'shared/pokemon_sprites_shiny2' %>



    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
    <div id="articlestop">
      <h2 class="mb-1">The Golden Times</h2>
      <p>Daily Pokemon stories straight from Johto</p>

       <%= image_tag "hohoho.png", class: "hooh" %>


    </div>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
<a class="p-1 m-1" href="https://www.instagram.com/goldenrod.city.news/" target="_blank"><%= image_tag "insta.png", class: "socialicon" %></a> <!-- Instagram icon -->

          <a class="p-1 m-1" href="https://www.facebook.com/profile.php?id=61558581625939" target="_blank"><%= image_tag "facebook.png", class: "socialicon" %></a> <!-- Twitch icon -->

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0"> <!-- mx-auto for centering -->
        <li class="nav-item">
           <%= link_to "News", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "PokeQuiz", pokequiz_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pokemon Tracker", tracker_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Staff", staff_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link donate-button" href="https://www.paypal.com/donate/?hosted_button_id=QCWFD79VTG9SY" target="_blank">Donate</a>
        </li>
              </ul>
       <div class="d-flex"> <!-- Flex container for icons -->

        <div>
            <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "navbar-link" do %>
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: "user-image", alt: "User Image" %>
          <% else %>
            <%= image_tag "default.jpg", class: "user-image", alt: "User Image" %>
          <% end %>
        <% end %>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-link" %>
        </div>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "navbar-link" %>
        <%= link_to "Login", new_user_session_path, class: "navbar-link" %>
      <% end %>
    </div>
  </div>
</nav>